### ISSUE TITLE
Suggestion on chat

### ISSUE THREAD

**Issue by cjzhao72** [yoav-zibin/default-theme#4]
I think it will be more convenient for the user that if one send a chat message, the other could click and reply

**Comment by yoav-zibin** [comment]
So, you can do several things with a notification: close ("X" symbol), click on the avatar, or click.
I decided that a click on the notification leads to the relevant match (all chat is associated with some match).
If you want to reply, you click on the avatar, and then type your reply (so just an extra click :))

**Comment by yoav-zibin** [comment]
I've actually implemented your suggestion now :)
After clicking on a chat, I load both the match AND I show the bottom sheet so you can easily reply :)
