### ISSUE TITLE
Detecting random opponent

### ISSUE THREAD

**Issue by ismailmustafa** [yoav-zibin/default-theme#7]
Random opponent detection is a bit finicky. I go into incognito mode in an attempt to play against myself, however sometimes, when I select random opponent, it finds me, and other times, it pairs me with an "Unknown" opponent as shown below:

![image](https://cloud.githubusercontent.com/assets/6578679/14227389/272be248-f8ca-11e5-9a6c-ac8227b90773.png)

Any ideas?

**Comment by ismailmustafa** [comment]
I found a way to always play against a specific opponent using browsers by following these steps:

Recreate the problem:

1. open two windows http://www.multiplayer-gaming.com/v1/dist/#/main, one normal, one incognito
2. Click new game in the non-incognito one
3. Click share an invite link with your friends
4. Copy the link and paste it into the incognito browser. Do not open a new tab in the incognito browser, paste it into the current game session
5. Click back in the incognito browser, a notification should pop up saying you are invited to a game. Click it and make a move.
6. A game initiated notification will pop up in the non-incognito browser. You can now play against each other.

It's a little hacky but it works.

**Comment by yoav-zibin** [comment]
Correct, that is the best way :)
There is also an e2e test that does exactly that:
https://github.com/yoav-zibin/default-theme/blob/gh-pages/tests/e2e_tests.ts#L1239
